### ISSUE TITLE
ramdump showing username and password

### ISSUE THREAD

**Issue by dinomycle** [silkimen/cordova-plugin-advanced-http#162]
Hello all,
 we are using this plugin for our Android and iOS app, for one of our info security testing using frida tool for taking ramdump. we can see the username and password in the RAM DUMP taken after the login button is pressed, for the data which is send to the URL passed to the http plugin. 

How can i remove this data ? this seems to be a security issue right

**Comment by dinomycle** [comment]
can some one guide on the above issue ?

**Comment by silkimen** [comment]
Hi dinomycle, I've never used frida tool. What exactly is your problem? Can you please explain your use-case more in detail? Where do you enter your username and password? Where is this data stored?

**Comment by dinomycle** [comment]
1) I am using http with https://ionicframework.com/docs/native/http/ .
2) Create a test app with login form, login username and password text field and login button 
3) When login button is pressed. call a http url for authentication
import { HTTP } from '@ionic-native/http';
   let http = new HTTP
   http.setDataSerializer("json");
    let login_params = { "username":do_login_username , "password":do_login_password } 
   http.post( 'https://www.WEB_URL/' + 'validate_login',login_params, this.headers)
      .then(data => {

        console.log(data.status);
        console.log(data.data); // data received by server
        console.log(data.headers);
        

      })
      .catch(error => {

        console.log(error.status);
        console.log(error.error); // error message as string 
        console.log(error.headers);

      });
4) build the sample app using
 ionic cordova run android
5) Once the app shows in the mobile. click on login and enter username and password, lets say 
username we entered is testing_dino
password we entered is testing_password

6) Using frida dump, dump the RAMDUMP of the app. and search in the frida dump file. we can see the password and username . which means the username and password is in the memory and any hacker can get the data. 
https://mobileapphacking.com/2018/09/15/android-memory-dump/

after inserting lot of logs in the code flow, one location where the data is no cleared is when the plugin calls exec() function to call the java functions.

**Comment by silkimen** [comment]
Ok thanks, so the problem is in these lines [advanced-http.js#L88-L96](https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/www/advanced-http.js#L88-L96)? I don't see how to prevent that. Do you have an idea? As long as the code calling this function is not out of scope, the garbage collector will not clean up the closure. So it'll stay in memory.

But actually I don't see a high risk here. As you've also stated: you need to have the device rooted to dump the RAM. Otherwise you don't have a chance to access this kind of low level data.

**Comment by dinomycle** [comment]
The password is retained after the logout, 
 if there is any other method to clear all message data/variables (used by exec)

**Comment by silkimen** [comment]
"exec" is a function provided by Apache Cordova, it's not part of this plugin. So if the problem is caused by "exec", there's nothing I can do.

But even if it's a problem in the plugin code, the JS engine is using a garbage collector and therefore it's not possible to just clear the memory. There are no "malloc" and "free" functions to achieve this.

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem!
