### ISSUE TITLE
setSSLMode for browser - any options (paid development)

### ISSUE THREAD

**Issue by vosecek** [silkimen/cordova-plugin-advanced-http#166]
Is there any option for implement missing browser features (Pinning SSL certificate, Disabling SSL certificate check)?

If is it possible, please say price for implementing these two features.

**Comment by silkimen** [comment]
Hi vosecek, unfortunately I can't implement this features for the browser platform, because I'm using basic Web API functions. Browsers don't support messing up how the SSL / TLS connections are handled due to security risks. But maybe you can ask the guys at https://digitalbazaar.com/. They have implemented [forge](https://github.com/digitalbazaar/forge) which is an impressive TLS library written in JS. Maybe they will master to achieve this.

**Comment by vosecek** [comment]
Thanks for reply.
