### ISSUE TITLE
How to POST a null Object?

### ISSUE THREAD

**Issue by saridakis** [silkimen/cordova-plugin-advanced-http#177]
I am trying to post a NULL object by using cordova.plugin.http.setDataSerializer('json') serilizer, but I always get an object on the server (.Net Core, Web API 2). While all other posts work properly and the responses are  ok, when the object I am posting is NULL, the plugin sends an empty Object (not a null one. An empty object for c# means an object initialized with default values for no nullable types ).

According to this https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/www/helpers.js (line 216) data = data || {}; the plugin is always sending an object.

What am I doing wrong? Should I try to avoid that helper function? Is there any other way to implement the post with null object, by using 'json' serializer?

**Comment by chrisjdev** [comment]
The JSON spec doesn't specify what is allowed for top level items, but Apple's NSJSONSerialization method specifies that "The top level object is an NSArray or NSDictionary.", so I think that's why this plugin works the way it does. To workaround the plugin limitations, something like this may work if the object === null:                `cordova.plugin.http.setDataSerializer('utf8');
cordova.plugin.http.post(url, 'null', { 'Content-Type': 'application/json' });
cordova.plugin.http.setDataSerializer('json');`

**Comment by saridakis** [comment]
@chrisjdev thank you!!!! .... it works!!!! I would say that, this is little unorthodox way to post a json object but it works!!!! ... the trick actually is to send the string 'null'. I had tried the serializer with 'utf8', but I was sending an empty string ('') instead of a string with 'null'...

Besides that, I think that this should be handled by the plugin, as well as the serialization of the json response (which of course is string), should be done on the thread of actual post and not by the client (by calling JSON.parse(response.data) which is much slower because is the same thread as UI, at least in IONIC). The response.data should be a pure Object.

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem!
