### ISSUE TITLE
Error in uploadfile 

### ISSUE THREAD

**Issue by sheetalpatnage** [silkimen/cordova-plugin-advanced-http#208]
We are using this plugin for image upload. On android device it workes fine. But on ios device if  we try to select image from gallery and click on upload. We are getting error as 'could not add file to post body'. Http 500 error. What could be reason?

**Comment by silkimen** [comment]
HTTP status code 500 stands for "internal server error". You'll need to get some log files from the backend and check what's going on. Otherwise it'll be impossible to solve the problem.

Closing this, feel free to open a new issue, if this won't solve your problem!

**Comment by sta55en** [comment]
Are you using Capacitor? I'm seeing this on Capacitor.

**Comment by florian72810** [comment]
I got this error today. The problem was easy: my file did not exist. Getting an error status 500 for a missing file is a little confusing. Unfortunately, I don't have server logs access here, so I cannot confirm if the plugin or the server created the error.

If you encountered again a 500 error with the message "could not add file to post body", check if the file you tried to upload exists.
