### ISSUE TITLE
Body not present in case of an HTTP error

### ISSUE THREAD

**Issue by Enrico204** [silkimen/cordova-plugin-advanced-http#222]
If an HTTP error is returned, the body data is discarded. Instead, I think that body data should always be returned to the caller, as the HTTP standard specification says that (almost) any HTTP status code can have a body in the response, not only 2xx. This is particularly needed in RESTful APIs.

**Comment by silkimen** [comment]
Actually, the body is not discarded. The `error` property contains the decoded body if it's available (see screenshots). I know this is a little bit confusing, but changing this would break compatibility with older versions.

`error` containing body:
<img width="904" alt="Bildschirmfoto 2019-06-13 um 12 50 47" src="https://user-images.githubusercontent.com/4717881/59427769-baa15400-8ddb-11e9-9509-be9523d2a5ff.png">

`error` containing exception message, because we didn't receive a body:
<img width="898" alt="Bildschirmfoto 2019-06-13 um 13 06 13" src="https://user-images.githubusercontent.com/4717881/59427886-0b18b180-8ddc-11e9-8b88-9fb6a60e1302.png">

**Comment by Enrico204** [comment]
Ah sorry, I didn't notice that. Thank you :-)
