### ISSUE TITLE
cordova.plugin.http.downloadFile removes body when sending request

### ISSUE THREAD

**Issue by Joseph-Ryu** [silkimen/cordova-plugin-advanced-http#223]
Consider below code:

url = 'someUrl.com'
body = { a: 1, b: 2};
cordova.plugin.http.downloadFile(encodeURI(url), body, {}, systemPath)

execution of downloadFile then will convert url to 'someUrl.com?a=1&b=2' and remove body from the request.

Is there a way to avoid that? I want the request to still have the body. Changed URL is not an issue

**Comment by silkimen** [comment]
Hi Joseph,
no this is not supported, because downloading a file is implemented via GET request, which does not support sending a message body. The second param is meant to be used for adding query params to the url. So it's behaving as expected.

The RFC spec states that "A server SHOULD read and forward a message-body on any request; if the request method does not include defined semantics for an entity-body, then **the message-body SHOULD be ignored when handling the request**." (see https://tools.ietf.org/html/rfc2616#section-4.3). And the description for the GET request states that "The GET method means retrieve whatever information (in the form of an entity) is identified by the **Request-URI**" (see https://tools.ietf.org/html/rfc2616#section-9.3)

==> it's not a good idea to include a message body in GET request

**Comment by Liam-Ryan** [comment]
Can I ask why download was implemented as get rather than post request? I'm running into an issue where we are providing a base64 image to a download url which is providing a formatted pdf but we're hitting the get limits ( I know get itself as a protocol does not have a limit but in reality it's around 2kb )

I can ask in a different thread if you prefer, I don't know Joseph-Ryu this just seemed very relevant to what I'm trying to do. I'm happy to go ahead and implement myself I was just wondering if you had tried to use post and run into issues? 

Thanks for the great work on the plugin

**Comment by Joseph-Ryu** [comment]
Is there a way for me to use POST instead for downloading?

**Comment by silkimen** [comment]
You can fork this plugin and change it yourself. Please use [StackOverflow](https://stackoverflow.com/questions/tagged/cordova-plugin-advanced-http) for this kind of questions.
