### ISSUE TITLE
Cleartext HTTP traffic to ipadress not permitted

### ISSUE THREAD

**Issue by Proxtx** [silkimen/cordova-plugin-advanced-http#237]
My config includes
<allow-intent href="*" />
<allow-navigation href="http://*" />
    <access origin="*" />

**Comment by minh1996bk** [comment]
today my app can't get data from my server. i debug and get error like this: There was an error with the request: java.net.UnknownServiceException: CLEARTEXT communication to myserver not permitted by network security policy. I use ionic 3 and cordova-plugin-advanced-http version ^1.11.1

**Comment by silkimen** [comment]
Hey guys, this problem is occurring when you set your android target SDK level to 28+. It's because of Google changing some security behaviour see https://developer.android.com/about/versions/pie/android-9.0-changes-28#tls-enabled for more info. You'll need to use a HTTPS backend with TLS or you need to whitelist the HTTP domains. This problem is not related to this plugin.
