### ISSUE TITLE
Http interceptor

### ISSUE THREAD

**Issue by SaltyPotato** [silkimen/cordova-plugin-advanced-http#246]
Hi,

I was wondering if this plugin supports an angular http interceptor. If not, is there any other library I can use to do this?

Thanks in advance!

**Comment by HighSoftWare96** [comment]
I was wondering that too but I think this is not actually possible right now. Maybe this can be useful: #186

**Comment by silkimen** [comment]
Hey guys, this is out of scope of this plugin, because it's meant to be a generic cordova plugin not specialized on angular. But you can try sneas adapter (never tried it myself though), maybe it'll solve your problem: https://github.com/sneas/ionic-native-http-connection-backend

If it's working for you; i'd be glad to receive some feedback 👍😉

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem! 👍
