### ISSUE TITLE
[Feature] Support for boolean and number parameter values

### ISSUE THREAD

**Issue by lucascrandle** [silkimen/cordova-plugin-advanced-http#277]
**Is your feature request related to a problem? Please describe.**
Passing in numbers or boolean values in the params object throws an error:
`logger.service.ts:30 Error: advanced-http: "params" option needs to be an dictionary style object, <params: {[key: string]: string | string[]}>`

**Describe the solution you'd like**
Allow for numbers and boolean values to be passed. So an example url would look like: `www.example.com?boolvalue=true&numvalue=3&stringvalue="test"`

```js
this.http.sendRequest(url, { method: "get", params: {"stringvalue":"test", "boolvalue":true, "numvalue":3}})
```

**Describe alternatives you've considered**
I can manually call the .toString() function for now but it would be nice to have this support.

**Comment by silkimen** [comment]
Hi Lucas, URL query params are always meant to be string values. There will be no quotes in the serialized params.

It is indeed possible to do an implicit `.toString()` call on the values (this was done on very old versions), but I prefer to have it explicitly. People used to end up with something like `www.example.com?params=[object Object]` because they didn't understand that the params object is not meant to be used for deep structures.

This plugin is meant to be a low level generic tool. If you want to have some comfort functions like this one mentioned here, you should implement a little wrapper in your code.

**Comment by lucascrandle** [comment]
@silkimen Ok that makes sense. Thank you for the response!
