### ISSUE TITLE
[Doc] Add Documentation Explaining Local Asset Load

### ISSUE THREAD

**Issue by Lindsor** [silkimen/cordova-plugin-advanced-http#342]
According to bug report #191 this plugin does not support loading local assets on the device.
When building a hybrid application this is a fairly common use case. 

If possible i would suggest adding a comment/documentation in the README.md file explaining this behavior and maybe a justification.

**Comment by silkimen** [comment]
Hi Lindsor, this is listed in the [FAQs](https://github.com/silkimen/cordova-plugin-advanced-http/wiki/FAQs#loading-local-files). I don't think it fits into the documentation, because it should focus on what is possible and how, not what is not possible. The FAQ section feels right to me for this kind of questions. What do you think @Lindsor?

**Comment by Lindsor** [comment]
Yeah i understand the focus on whats possible, and FAQ sounds OK to me.
I feel like this one might be an edge case though, since were dealing with hybrid applications and if your using JS directly it allows you to AJAX into local files i feel like most developers would assume thats natural for this plugin.

The only reason we are moving to using the plugin is because our info-security department is asking for certificate pinning, we would never have routed our AJAX through native if we could avoid it so expected the changes to be minimal from a "what can you do" perspective.

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem! 👍
