### ISSUE TITLE
Android Headers are not normalized (not returned in lowercase)

### ISSUE THREAD

**Issue by enayetn** [silkimen/cordova-plugin-advanced-http#35]
Hello,

I have observed that iOS headers are returned in lowercase whereas Android preserves the case sent by the resource. Is this expected? 

Thanks,

**Comment by silkimen** [comment]
Hi Nabil,
nope, we had decided to normalize the header keys by returning them in lowercase. We must have forgotten to implement it for Android. Thanks for the notice!

**Comment by nabil-nuvolo** [comment]
Just curious - why cast to lowercase?

**Comment by silkimen** [comment]
HTTP header keys are meant to be case-insensitive, see [RFC7230 - Section 4.2](https://tools.ietf.org/html/rfc7230#section-3.2). Accessing them with a normalized identifier is easier.

e.g. you don't want to check for both `Content-Encoding` and `content-encoding` just because one server decided to send it lowercase and another uppercase. So basically it's just a convenience function.

**Comment by enayetn** [comment]
I would request that a switch be enabled that allows the developer to control whether it is cast to lower case or not. Either that, or offer a getHeader function that takes whatever header I want to retrieve and casts it in the background. 

Thanks for your work on this!

**Comment by silkimen** [comment]
OK, I could implement a getter, but what do you need the case-preserving key for? You shouldn't rely on that, because basically every intermediate device can also change it.

And another problem is that iOS always returns  e.g. `Content-Encoding` even if the server responds with `CONTENT-ENCODING` or `content-encoding`. So basically iOS itself already canonicalizes it, but unfortunately only for the default headers.

See [here](https://developer.apple.com/documentation/foundation/httpurlresponse/1417930-allheaderfields):

> HTTP headers are case insensitive. To simplify your code, certain header field names are canonicalized into their standard form. For example, if the server sends a **content-length** header, it is automatically adjusted to be **Content-Length**.

On the other hand, it's a common practice to lowercase header keys. I'm also regularly working with node.js and the http module also lowercases header keys. See [here](https://nodejs.org/api/http.html):

> The keys of the returned object are the header names and the values are the respective header values. **All header names are lowercase**.

**Comment by enayetn** [comment]
Hi @silkimen thanks for your response. My understanding of the spec is that resource end points accepting headers should never consider case when creating header keys, thus they should **accept** case insensitive headers as a resource owner. 

However my understanding is that this library serves to bring requests back to a client. Having dealt with primary front end/clients for most of my career this is the first time I have encountered differently cased headers when comparing to the server response when inspecting in some mock web service tool. 

This is just my understanding as it is today, I will be plenty happy with consistency being implemented between iOS and Android just thought I would offer an enhancement request that I think would help avoid confusion. 

Thanks again! 😁

**Comment by silkimen** [comment]
Hi Nabil,
you are right, we will need to document this behavior to prevent confusion, just like the node.js docu does. Otherwise, other people will also be confused.

I'll fix the Android issue in upcoming v1.7.1

Thanks for your suggestion on this topic!
