### ISSUE TITLE
[Bug] [android] I/O error during system call, Connection reset by peer

### ISSUE THREAD

**Issue by defolly** [silkimen/cordova-plugin-advanced-http#368]
My app occasionally get an error when it requests the api (https) in Android, but most of the time it work well.  I don't know how to solve it，Is there anyone to help me with it?

**Comment by silkimen** [comment]
This message means that the server has closed the connection (see [what-does-connection-reset-by-peer-mean](https://stackoverflow.com/questions/1434451/what-does-connection-reset-by-peer-mean)). You'll need more information to find out the reason. You could try to get logs from the server side.

Please use [StackOverflow](https://stackoverflow.com/questions/tagged/cordova-plugin-advanced-http) for this kind of questions as your issue doesn't seem to be caused by a bug in this plugin.
