### ISSUE TITLE
Accept All Certs seems to not work with self signed certificates

### ISSUE THREAD

**Issue by mburger81** [silkimen/cordova-plugin-advanced-http#4]
We use on a local installed machine a webserver where we install our osgi bundl with our REST apis.
So we can not work with certificates, and also we can not install a signed certifcate, but we have installed a self signed one.

If we use `accaptAllCerts` with false obvisouly we get this error
`{error: "SSL handshake failed", status: 500} `
but if we set it to true we get another error
`{error: "There was an error with the request", status: 500} `

But it should work right?

**Comment by mburger81** [comment]
I also tried to copy my certificate to the folder requested and enable the ssl pinning.
But I get always the same error:
`{error: "There was an error with the request", status: 500}`

**Comment by silkimen** [comment]
Did you check log files of the server? And are you sure there is no problem with the REST services?
You could try disabling SSL on the server (just for testing purposes) and check if the problem still exists.

**Comment by mburger81** [comment]
Honestly we are not the maintainer of the webserver so we have a little bit problems to check this on server side. But on client side and on server side we do the same thing the only one thing changing is we call https instead of http.
On our tests, we found out if we set enableSSLPinning to true also the normal http calls which works great without this parameter, doesn't work anymore.
So I think there are a problem on this side.

**Comment by silkimen** [comment]
I've created a little demo project here: https://github.com/silkimen/cdv-http-demo
You need to disable domain name checking when you are enabling accepting all certs. Maybe this is the reason why it's not working for you?

**Comment by mburger81** [comment]
Okay I tested all this scenarios, so in both case `acceptAllCerts` or `sslPinning` we have always to set validateDomainName to `false`.

In this case both scenarios works,
```
acceptAllCerts = true
validateDomainName = false
enableSSLPinning = false
```
is working for all ssl certificates and
```
acceptAllCerts = false
validateDomainName = false
enableSSLPinning = true
```
is working for my self signed certificate file copied to `/www/certificates` folder.

So one question, why do you don't on  `acceptAllCerts` or `enableSSLPinning` automatically set `validateDomainName` to `false`?

Also I noticed, if I use `enableSSLPinning` we can not combine HTTP with HTTPS calls, Is it wanted like that?

**Comment by silkimen** [comment]
> So one question, why do you don't on acceptAllCerts or enableSSLPinning automatically set validateDomainName to false?

You are right with the first one. We could automatically disable `validateDomainName` when you enable `acceptAllCerts`. Maybe I'll implement this in our next version.

Enabling SSL-pinning means that the SSL certificate provided in the app must exactly match the one provided by the server. So basically, you tell the plugin to trust only this one certificate. You don't really need to check for the correct domain name, if you trust this one cert. But I think it still should be possible to validate the domain name, if you choose to do.

If this is not given, I'll need to check this. Are you sure your self-signed cert has "192.168.8.1" as common name?

> Also I noticed, if I use enableSSLPinning we can not combine HTTP with HTTPS calls, Is it wanted like that?

Actually, this is what I'd expect if I enable ssl-pinning. Because normally you have only one endpoint you want to communicate with.

But if you want to communicate with HTTP and HTTPS endpoints you can turn off ssl-pinning each time you want to communicate with HTTP endpoint and re-enable it if you want to communicate with HTTPS endpoint.

**Comment by mburger81** [comment]
Ok, 
I think we should be able to combine http and https calls.
Also I think there should be this scenario
a) Always accept http calls indipend on what you have have enabled on ssl, and perhapse disableHttp property to block them? 
b) acceptAllCertificates do no check cerificate
c) sslPinning check self signed certificate
d) if b and c are disabled then dellegate check to Android device. Not sure what is checkDomain. Is this standart certificate check as webview does? 

Also I think you should have only on method to set b, c and d. 

Perhapse I missunderstand something on the behavior and I'm writting wrong things 😁😁

What do you intend with common name for 192.168.8.1, the certificate is installed on our gateway which is an IoT gw and also a router so the io adress could be changed by user so it's not a static address

**Comment by silkimen** [comment]
I'm sorry, I didn't understand d). What do you mean with "delegate check to Android"?

Checking the domain name is default behaviour on HTTPS connections. And even if you install a self-signed cert you need to provide a common name, which is actually the domain name.

If you don't have a static domain name, I strongly recommend using pinned SSL otherwise you won't have any security. But in this case you need to disable domain name checking.

I think you need to read more about HTTPS connections and SSL certs. SSL certs do bind together:
- a domain name (server or host name)
- an organizational identity

**Comment by silkimen** [comment]
Closing as all mentioned scenarios are working.
