### ISSUE TITLE
Doesn't encode arrays correctly as HTTP GET parameter on Android

### ISSUE THREAD

**Issue by AlekseiFalshtynskii** [silkimen/cordova-plugin-advanced-http#45]
Hello!
How can I send a GET request with an array parameter?
For example,
http://localhost:8081/rest/v1/payments?clientId=101216&accountIdList=101510&accountIdList=101511

accountIdList sent only so:
http://localhost:8081/rest/v1/payments?clientId=101216&accountIdList=[101510,101511]

Thank you.

**Comment by silkimen** [comment]
Hi Aleksei,

I've checked how to send arrays in a HTTP GET request. Unfortunately, there is no specification about that. You can have a look into [this StackOverflow discussion](https://stackoverflow.com/a/3061292).

So basically, I can think about at least 4 ways to encode arrays:
1. ?myArray[]=valA&myArray[]=valB
2. ?myArray=[valA,valB]
3. ?myArray=valA&myArray=valB
4. ?myArray=valA,valB

The first one seems to be the best as it can be processed by most of backend systems, so it would be good to implement this one.

I've checked which one is implemented atm and realized:
* iOS is using implementation no 1
* Android is using implementation no 2

That's obviously a bug, because it should be implemented identically for both platforms. Should be fixed to use first implementation.

**Comment by AlekseiFalshtynskii** [comment]
Hi Sefa!
Thank you!
