### ISSUE TITLE
Failed with Adobe PhoneGap Build

### ISSUE THREAD

**Issue by softshape** [silkimen/cordova-plugin-advanced-http#47]
When compiling project with Adobe PhoneGap Build service - https://build.phonegap.com/ - it fails.

> /project/src/com/synconset/cordovahttp/CordovaHttpDownload.java:18: error: package org.apache.cordova.file does not exist
> import org.apache.cordova.file.FileUtils;
>                               ^
> /project/src/com/synconset/cordovahttp/CordovaHttpDownload.java:49: error: cannot find symbol
>                 JSONObject fileEntry = FileUtils.getFilePlugin().getEntryForFile(file);
>                                        ^
>   symbol:   variable FileUtils
>   location: class CordovaHttpDownload
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> 2 errors
> :compileDebugJavaWithJavac FAILED
> 
> FAILURE: Build failed with an exception.

There's a mention of cordova-plugin-file in the log also:

> Fetching plugin "cordova-plugin-advanced-http@^1.8.1" via npm
> Installing "cordova-plugin-advanced-http" at "1.8.1" for android
> Fetching plugin "cordova-plugin-file@>=2.0.0" via npm
> Installing "cordova-plugin-file" at "5.0.0" for android
> Plugin doesn't support this project's cordova-android version. cordova-android: 6.1.2, failed version requirement: >=6.3.0
> Skipping 'cordova-plugin-file' for android

**Comment by 123dma** [comment]
same problem here.

**Comment by 123dma** [comment]
hello, I found the problem
1 - update your phonegap app version to last version

**Comment by softshape** [comment]
123dma, where exactly it should be updated?

**Comment by 123dma** [comment]
Hello, try to add in your config.xml this options 

 <plugin name="cordova-plugin-device" source="npm" spec="~1.1.6" />
  <plugin name="cordova-plugin-dialogs" source="npm" spec="~1.3.3" />
  <plugin name="cordova-plugin-file" source="npm" spec="~4.3.3" />
  <plugin name="cordova-plugin-inappbrowser" source="npm" spec="~1.7.1" />
  <plugin name="cordova-plugin-network-information" source="npm" spec="~1.3.3" />

remove the older´s

I did here and had sucess

**Comment by silkimen** [comment]
This problem is caused by the fact that this plugin depends on "cordova-plugin-file" >= v2.0.0, which causes cordova to load the latest version of this plugin during `cordova prepare` when there is no pinned version.

Basically, this is no problem, but when you are running a cordova version < 6.3.0, current version of the file plugin is not compatible and it's not installed during cordova prepare. That's the reason why it's also mentioned in the log.

You can prevent this issue by adding following line in your config.xml (pinning the version of file plugin to 4.3.3):

```
<plugin name="cordova-plugin-file" spec="4.3.3" />
```
