### ISSUE TITLE
undefined sendRequest

### ISSUE THREAD

**Issue by mazkaaa** [silkimen/cordova-plugin-advanced-http#477]
**Hello!**
i've been using http sendRequest to the rest api backend endpoint but got undefined result.
<img width="366" alt="image" src="https://user-images.githubusercontent.com/5271698/189075597-67b47ab2-9341-4cd9-8598-486750820473.png">

<img width="956" alt="image" src="https://user-images.githubusercontent.com/5271698/189078965-635847a2-3315-47e5-9622-6f704bf297a5.png">

I already tried to setServerTrustMode to nocheck but it wont print the log. any idea?

**Comment by silkimen** [comment]
You implemented the success handler but didn't provide the fail handler function and your request is most likely failing. Just an idea: try to use the `Bearer` authentication scheme for your JWT token instead of `JWT` which is not a registered IANA scheme.

But your problem is not related at all to this plugin, therefore:

Please read the [documentation](https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/README.md) carefully. We primarily use GitHub as an issue tracker; for usage and support questions, please check out these resources below. Thanks! 

* README.md: https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/README.md
* StackOverflow: https://stackoverflow.com/questions/tagged/cordova-plugin-advanced-http using the tag `cordova-plugin-advanced-http`
* Wiki: https://github.com/silkimen/cordova-plugin-advanced-http/wiki
