### ISSUE TITLE
TLSConfiguration.java

### ISSUE THREAD

**Issue by vivekananda8909** [silkimen/cordova-plugin-advanced-http#483]
@silkimen 

We are using Veracode to find security vulnerabilities in our app. We got one issue "Selection of Less-Secure Algorithm During Negotiation ('Algorithm Downgrade')".

I followed the steps which you suggested in #423

<preference name="AndroidBlacklistSecureSocketProtocols" value="SSLv3,TLSv1" />,  but no luck

Can you suggest  any other alternate to fix Veracode scan issue.

Please find the screen shot for you reference.

<img width="1312" alt="Screen Shot 2022-10-20 at 9 53 42 AM" src="https://user-images.githubusercontent.com/36451679/196969057-b82e6884-3cb6-4b92-8fa2-7dc4ac429c54.png">

**Comment by silkimen** [comment]
Not sure, but this looks like a false positive to me. Because line 47 is only applying the cached socket factory. It doesn't change any security related stuff.

The socket factory is created in line 55. That's also where the blacklist is applied. You can check the 'TLSSocketFactory.Java' class. The given blacklisted names will be filtered from enabled protocols.

**Comment by vivekananda8909** [comment]
@silkimen 

Thanks for the quick response. Anything you can also help us or confirm about these low priority flaws.

<img width="1321" alt="Screen Shot 2022-10-26 at 4 32 47 PM" src="https://user-images.githubusercontent.com/36451679/198132126-8b8b1927-4b19-4c51-ac24-18f18c4d5b10.png">

<img width="1321" alt="Screen Shot 2022-10-26 at 4 32 47 PM" src="https://user-images.githubusercontent.com/36451679/198132098-c6604e55-7384-4f04-9410-ce90ec771483.png">

**Comment by silkimen** [comment]
Please use [StackOverflow](https://stackoverflow.com/questions/tagged/cordova-plugin-advanced-http) for this kind of questions.
