### ISSUE TITLE
can this plugin support  cancel  operation ?

### ISSUE THREAD

**Issue by CNzhangs** [silkimen/cordova-plugin-advanced-http#50]
hi,can this plugin support  cancel  http request for Android?Or how can i implement this function base the plugin ?

**Comment by silkimen** [comment]
Hi CNzhangs,

this plugin does not support canceling ongoing http requests. And honestly I don't know how to implement it, because http-request (Android library, which we are using) doesn't seem to support it. But feel free to fork this plugin and start experimenting! Maybe you can modify the library accordingly.
