### ISSUE TITLE
http.delete not works, it doesn't send the parameters

### ISSUE THREAD

**Issue by Hanzofm** [silkimen/cordova-plugin-advanced-http#89]
Hi, I'm trying to do a delete request to my api but it returns that the parameters are missing:

```
this.http.delete(path, data,headers)
      .then(response => {
        return JSON.parse(response.data);
      })
      .catch(error => {return this.handleError(error)});
```

It seems that delete function not sends the body data. **The same body with postman works fine.**
With post, and put there are not problems, What would be the problem?

Info:
```
Android platform: 6.4.0
Ionic version 3.9.2
Ionic native http: 4.5.3
Http Plugin version: 1.11.0
```

**Comment by chax** [comment]
This plugin doesn't allow sending request body for DELETE request.
Your second parameter (data) is not what is going to be sent as request body, but as query parameters (like GET request).
Technically server which processes DELETE request can accept request body but it's not part of HTTP standard.
See https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html

**Comment by Hanzofm** [comment]
Some workaround to send it? The backend server accepts body on delete request and are necessary to my project

**Comment by chax** [comment]
If you don't depend on allowAllCerts or enableSSLPinning for your self-signed-certificates, then rather use Angular HTTP Service, it is much more flexible but depends on Browser security policy to decide which certificates are trusted and which are not. If your Cordova App is not Angular based, you have jQuery or some other javascript framework to help you.

**Comment by Hanzofm** [comment]
My problem is that I use ionic and need to use this client to patch cors restriction on WBKView Engine.

**Comment by silkimen** [comment]
Hi Hanzofm,

it's not a good practice to send payload within a DELETE request, because there is no defined behavior to be expected on the backend. It can cause the server to reject the request. There are also web application firewalls and proxies which don't pass such kind of requests.

See [RFC7231#section-4.3.5](https://tools.ietf.org/html/rfc7231#section-4.3.5):

> A payload within a DELETE request message has no defined semantics;
   sending a payload body on a DELETE request might cause some existing
   implementations to reject the request.

I won't implement this kind of feature, because it doesn't respect RFC specs, sorry!

**Comment by BassamHabash** [comment]
Hi @silkimen 
Is there any update for this issue as we are running into the same issues.
